import { Exercise } from '@/types/exercise';

const BASE = 'https://hsnym0419419.github.io/workout-videos';
const IMG = BASE;

export const EXERCISES: Exercise[] = [
  {
    id: '1',
    title: 'Jumping Jacks',
    description: 'Stand upright, jump to a position with legs spread wide and arms overhead, then return.',
    duration: 30,
    rest: 10,
    videoId: 'c4DAnQ6DtF8',
    thumbnail: `${IMG}/jumpingjack.jpeg`,
    mediaUrl: `${BASE}/jumpingjack.mov`,
    mediaType: 'video',
    muscleGroup: 'Full Body',
    difficulty: 'beginner',
    repType: 'single',
    repCount: 30,
  },
  {
    id: '2',
    title: 'Wall Sit',
    description: 'Slide your back down a wall until thighs are parallel to the floor. Hold the position.',
    duration: 30,
    rest: 10,
    videoId: 'y-wV4Venusw',
    thumbnail: `${IMG}/wallsit.jpeg`,
    mediaUrl: `${IMG}/wallsit.jpeg`,
    mediaType: 'image',
    muscleGroup: 'Legs',
    difficulty: 'beginner',
    repType: 'timed',
  },
  {
    id: '3',
    title: 'Push-Ups',
    description: 'Lower your body until chest nearly touches the floor. Push back up. Keep core tight.',
    duration: 30,
    rest: 10,
    videoId: 'IODxDxX7oi4',
    thumbnail: `${IMG}/pushup.jpeg`,
    mediaUrl: `${BASE}/pushup.mov`,
    mediaType: 'video',
    muscleGroup: 'Chest / Triceps',
    difficulty: 'intermediate',
    repType: 'single',
    repCount: 20,
  },
  {
    id: '4',
    title: 'Abdominal Crunches',
    description: 'Lie on back, knees bent. Curl shoulders toward knees using abdominal muscles.',
    duration: 30,
    rest: 10,
    videoId: 'Xyd_fa5zoEU',
    thumbnail: `${IMG}/crunch.jpeg`,
    mediaUrl: `${BASE}/crunch.mov`,
    mediaType: 'video',
    muscleGroup: 'Core',
    difficulty: 'beginner',
    repType: 'single',
    repCount: 20,
  },
  {
    id: '5',
    title: 'Step-Up onto Chair',
    description: 'Step up onto a sturdy chair, alternating feet. Maintain an upright posture.',
    duration: 30,
    rest: 10,
    videoId: 'msLem_LoXWo',
    thumbnail: `${IMG}/stepup.jpeg`,
    mediaUrl: `${BASE}/stepups.mp4`,
    mediaType: 'video',
    muscleGroup: 'Legs / Glutes',
    difficulty: 'intermediate',
    repType: 'bilateral',
    repCount: 10,
  },
  {
    id: '6',
    title: 'Squats',
    description: 'Stand with feet shoulder-width apart. Lower as if sitting in a chair, then stand.',
    duration: 30,
    rest: 10,
    videoId: 'aclHkVaku9U',
    thumbnail: `${IMG}/squat.jpeg`,
    mediaUrl: `${BASE}/squat.mov`,
    mediaType: 'video',
    muscleGroup: 'Legs / Glutes',
    difficulty: 'beginner',
    repType: 'single',
    repCount: 15,
  },
  {
    id: '7',
    title: 'Triceps Dips',
    description: 'Using a chair, lower your body by bending elbows. Push back up to straighten arms.',
    duration: 30,
    rest: 10,
    videoId: 'jwUqHW0FmIE',
    thumbnail: `${IMG}/tricepsdips.jpeg`,
    mediaUrl: `${BASE}/tricepsdips.mov`,
    mediaType: 'video',
    muscleGroup: 'Triceps',
    difficulty: 'intermediate',
    repType: 'single',
    repCount: 15,
  },
  {
    id: '8',
    title: 'Plank',
    description: 'Hold a push-up position with arms straight. Keep body straight from head to heels.',
    duration: 30,
    rest: 10,
    videoId: 'B296mZDhrP4',
    thumbnail: `${IMG}/plank.jpeg`,
    mediaUrl: `${IMG}/plank.jpeg`,
    mediaType: 'image',
    muscleGroup: 'Core',
    difficulty: 'intermediate',
    repType: 'timed',
  },
  {
    id: '9',
    title: 'High Knees',
    description: 'Run in place, bringing knees up to waist height. Keep a fast, steady pace.',
    duration: 30,
    rest: 10,
    videoId: 'ZZZoCNMU48U',
    thumbnail: `${IMG}/highknee.jpeg`,
    mediaUrl: `${BASE}/highknee.mov`,
    mediaType: 'video',
    muscleGroup: 'Full Body',
    difficulty: 'intermediate',
    repType: 'bilateral',
    repCount: 20,
  },
  {
    id: '10',
    title: 'Lunges',
    description: 'Step forward with one leg, lowering your hip until both knees are at 90°. Alternate legs.',
    duration: 30,
    rest: 10,
    videoId: 'QOVaHwm-Q6U',
    thumbnail: `${IMG}/lunge.jpeg`,
    mediaUrl: `${BASE}/lunge.mov`,
    mediaType: 'video',
    muscleGroup: 'Legs / Glutes',
    difficulty: 'beginner',
    repType: 'bilateral',
    repCount: 8,
  },
  {
    id: '11',
    title: 'Push-Up & Rotation',
    description: 'Perform a push-up, then rotate to a side plank, extending arm upward. Alternate sides.',
    duration: 30,
    rest: 10,
    videoId: 'qHQ_E-f5278',
    thumbnail: `${IMG}/pushup.jpeg`,
    mediaUrl: `${BASE}/pushupandrotation.mov`,
    mediaType: 'video',
    muscleGroup: 'Chest / Core',
    difficulty: 'advanced',
    repType: 'bilateral',
    repCount: 3,
  },
  {
    id: '12',
    title: 'Side Plank',
    description: 'Lie on your side, prop yourself on one forearm. Keep body straight. Switch sides halfway.',
    duration: 30,
    rest: 0,
    videoId: 'K2x8Om13Yhg',
    thumbnail: `${IMG}/sideplank.jpeg`,
    mediaUrl: `${BASE}/sideplank_short.mov`,
    mediaType: 'video',
    workoutMediaUrl: `${BASE}/sideplank.mov`,
    workoutMediaType: 'video',
    muscleGroup: 'Core / Obliques',
    difficulty: 'intermediate',
    repType: 'timed',
  },
];

export const TOTAL_WORKOUT_DURATION = EXERCISES.reduce(
  (acc, ex) => acc + ex.duration + ex.rest,
  0
);
